name: CI Integration Test

on:
  push:
    branches: [main]

jobs:
  continious-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create stage.properties
        run: |
          mkdir -p src/test/resources/config
          cat <<EOF > src/test/resources/config/stage.properties
          baseUrl=${{ secrets.BASEURL }}
          baseApiUrl=${{ secrets.BASEAPIURL }}
          companyId=${{ secrets.COMPANYID }}
          validEmailLogin=${{ secrets.VALIDEMAILLOGIN }}
          validPasswordLogin=${{ secrets.VALIDPASSWORDLOGIN }}
          EOF

      - name: Run Auth Integration Tests
        run: ./gradlew test -Psuite=ci.xml -Penv=stage