name: Automated Testing CI

on:
  push:
    branches:
      - '**' # Akan berjalan otomatis setiap kali ada push ke branch manapun

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Install Chrome Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Inject Configuration via GitHub Secrets
        run: |
          mkdir -p src/test/resources/config
          echo "baseUrl=${{ secrets.BASE_URL }}" > src/test/resources/config/stage.properties
          echo "baseApiUrl=${{ secrets.BASE_API_URL }}" >> src/test/resources/config/stage.properties
          echo "validEmailLogin=${{ secrets.VALID_EMAIL_LOGIN }}" >> src/test/resources/config/stage.properties
          echo "validPasswordLogin=${{ secrets.VALID_PASSWORD_LOGIN }}" >> src/test/resources/config/stage.properties

      - name: Run Tests
        run: ./gradlew clean test -Dbrowser=chrome -Denv=stage
        env:
          GITHUB_ACTIONS: true
          CHROMEDRIVER_PATH: /usr/bin/chromedriver # Memberitahu DriverManager lokasi driver yang baru diinstal

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Automation-Test-Report
          path: build/reports/
          retention-days: 7